.TH Correlations "" "2011\[en]04\[en]26 20:25 CET" 
.SS Description
.PP
This template will return the correlation matrix of supplied numerical
variables.
.SS Variable description
.PP
3 variables provided.
.PP
The highest correlation coefficient (0.2364) is between \[lq]it.edu\[rq]
and \[lq]age\[rq] and the lowest (\[en]0.049) is between
\[lq]it.leisure\[rq] and \[lq]age\[rq].
It seems that the strongest association (r=0.2364) is between
\[lq]it.edu\[rq] and \[lq]age\[rq].
.PP
Higly correlated (r < 0.7 or r > 0.7) variables: -
.PP
Uncorrelated (\[en]0.2 < r < 0.2) variables: * \[lq]age\[rq] -
\[lq]it.leisure\[rq] * \[lq]it.edu\[rq] - \[lq]it.leisure\[rq]
.SS Correlation matrix
.PP
[IMAGE: image (7abdf648965ac14c778c4d61dddc7023.png)]
.SH AUTHORS
(Username not set) (E-mail address not set).
