.\"t
.TH Crosstable "" "2011\[en]04\[en]26 20:25 CET" 
.SS Description
.PP
Returning the Chi-squared test of two given variables with count,
percentages and Pearson's residuals table.
.SS Variable description
.PP
Two variables specified: * \[lq]gender\[rq] (\[lq]Gender\[rq]) with 709
and * \[lq]dwell\[rq] (\[lq]Dwelling\[rq]) with 709 valid values.
.SS Counts
.PP
.TS
tab(@);
l l l l.
T{
T}@T{
\f[B]city\f[]
T}@T{
\f[B]small town\f[]
T}@T{
\f[B]village\f[]
T}
_
T{
male
T}@T{
380
T}@T{
30
T}@T{
22
T}
T{
female
T}@T{
262
T}@T{
6
T}@T{
9
T}
.TE
.SS Percentages
.PP
.TS
tab(@);
l l l l.
T{
T}@T{
\f[B]city\f[]
T}@T{
\f[B]small town\f[]
T}@T{
\f[B]village\f[]
T}
_
T{
male
T}@T{
0.5360
T}@T{
0.0423
T}@T{
0.0310
T}
T{
female
T}@T{
0.3695
T}@T{
0.0085
T}@T{
0.0127
T}
.TE
.SS Row percentages
.PP
.TS
tab(@);
l l l l.
T{
T}@T{
\f[B]city\f[]
T}@T{
\f[B]small town\f[]
T}@T{
\f[B]village\f[]
T}
_
T{
male
T}@T{
0.8796
T}@T{
0.0694
T}@T{
0.0509
T}
T{
female
T}@T{
0.9458
T}@T{
0.0217
T}@T{
0.0325
T}
.TE
.SS Column percentages
.PP
.TS
tab(@);
l l l l.
T{
T}@T{
\f[B]city\f[]
T}@T{
\f[B]small town\f[]
T}@T{
\f[B]village\f[]
T}
_
T{
male
T}@T{
0.5919
T}@T{
0.8333
T}@T{
0.7097
T}
T{
female
T}@T{
0.4081
T}@T{
0.1667
T}@T{
0.2903
T}
.TE
.SS Chi-squared test
.PP
.TS
tab(@);
l l l l.
T{
T}@T{
\f[B]X-squared\f[]
T}@T{
\f[B]df\f[]
T}@T{
\f[B]p-value\f[]
T}
_
T{
X-squared
T}@T{
9.72
T}@T{
2.00
T}@T{
0.01
T}
.TE
.PP
It seems that a real association can be pointed out between
\f[I]gender\f[] and \f[I]dwell\f[] by the \f[I]Pearson's Chi-squared
test\f[] (χ=9.7188 at the degree of freedom being 2) at the significance
level of 0.0078.
Based on Goodman and Kruskal's lambda it seems that \f[I]dwell\f[]
(λ=0.7581) has an effect on \f[I]gender\f[] (λ=0) if we assume both
variables to be nominal.
The association between the two variables seems to be weak based on
Cramer's V (0.0828).
.SS Pearson's residuals
.PP
.TS
tab(@);
l l l l.
T{
T}@T{
\f[B]city\f[]
T}@T{
\f[B]small town\f[]
T}@T{
\f[B]village\f[]
T}
_
T{
male
T}@T{
\[en]2.9409
T}@T{
2.8277
T}@T{
1.1713
T}
T{
female
T}@T{
2.9409
T}@T{
\[en]2.8277
T}@T{
\[en]1.1713
T}
.TE
.SS Mosaic chart
.PP
[IMAGE: image (66ba5aa603e08fec150848bb688f0953.png)]
.SH AUTHORS
(Username not set) (E-mail address not set).
