.\"t
.TH Descriptive "" "2011-04-26 20:25 CET" "statistics"
.SS Description
.PP
This template will return descriptive statistics and frequency table of
a categorical variable.
.SS \f[I]gender\f[] ("Gender")
.PP
The dataset has \f[I]709\f[] observations with \f[I]673\f[] valid values
(missing: \f[I]36\f[]) in \f[I]gender\f[] ("Gender"), which seems to be
a qualitative variable.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]gender\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]%\f[]
T}@T{
\f[B]Cumul. N\f[]
T}@T{
\f[B]Cumul. %\f[]
T}
_
T{
male
T}@T{
410
T}@T{
60.9212
T}@T{
410
T}@T{
60.9212
T}
T{
female
T}@T{
263
T}@T{
39.0788
T}@T{
673
T}@T{
100
T}
T{
Total
T}@T{
673
T}@T{
100
T}@T{
673
T}@T{
100
T}
.TE
.SS Barplot
.PP
[IMAGE: image (3a46554ee29cd4dfe45dda5016464658.png)] (3a46554ee29cd4dfe45dda5016464658-hires.png)
.PP
It seems that the highest value is \f[I]2\f[] which is exactly 2 times
higher than the smallest value (\f[I]1\f[]).
.PP
The most frequent value is \f[I]male\f[].
.SS Description
.PP
This template will return descriptive statistics and frequency table of
a categorical variable.
.SS \f[I]dwell\f[] ("Dwelling")
.PP
The dataset has \f[I]709\f[] observations with \f[I]662\f[] valid values
(missing: \f[I]47\f[]) in \f[I]dwell\f[] ("Dwelling"), which seems to be
a qualitative variable.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]dwell\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]%\f[]
T}@T{
\f[B]Cumul. N\f[]
T}@T{
\f[B]Cumul. %\f[]
T}
_
T{
city
T}@T{
599
T}@T{
90.4834
T}@T{
599
T}@T{
90.4834
T}
T{
small town
T}@T{
33
T}@T{
4.9849
T}@T{
632
T}@T{
95.4683
T}
T{
village
T}@T{
30
T}@T{
4.5317
T}@T{
662
T}@T{
100
T}
T{
Total
T}@T{
662
T}@T{
100
T}@T{
662
T}@T{
100
T}
.TE
.SS Barplot
.PP
[IMAGE: image (a370513c6bd94251e700ff5fea9dd33f.png)] (a370513c6bd94251e700ff5fea9dd33f-hires.png)
.PP
It seems that the highest value is \f[I]3\f[] which is exactly 3 times
higher than the smallest value (\f[I]1\f[]).
.PP
The most frequent value is \f[I]city\f[].
.PP
   *   *   *   *   *
.PP
This report was generated with R (http://www.r-project.org/) (2.14.0)
and rapport (http://al3xa.github.com/rapport/) (0.2) in 0.769 sec on
x86_64-unknown-linux-gnu platform.
.PP
[IMAGE: image (images/logo.png)]
.SH AUTHORS
Rapport package team \@ https://github.com/aL3xa/rapport.
