.\"t
.TH Example "" "2011-04-26 20:25 CET" "template"
.SS Description
.PP
This template demonstrates the basic features of rapport.
We all hope you will like it!
.SS Début
.PP
Hello, world!
.PP
I have just specified a \f[I]Variable\f[] in this template named to
\f[B]leisure\f[].
The label of this variable is "Internet usage in leisure time (hours per
day)".
.PP
And wow, the mean of \f[I]leisure\f[] is \f[I]3.1994\f[]!
.SS Descriptive statistics
.PP
.TS
tab(@);
l l l l l l l.
T{
\f[B]Min.\f[]
T}@T{
\f[B]1st Qu.\f[]
T}@T{
\f[B]Median\f[]
T}@T{
\f[B]Mean\f[]
T}@T{
\f[B]3rd Qu.\f[]
T}@T{
\f[B]Max.\f[]
T}@T{
\f[B]NA\[aq]s\f[]
T}
_
T{
0.000
T}@T{
2.000
T}@T{
3.000
T}@T{
3.199
T}@T{
4.000
T}@T{
12.000
T}@T{
37.000
T}
.TE
.PP
The 5 highest values are: \f[I]12\f[], \f[I]12\f[], \f[I]10\f[],
\f[I]10\f[] and \f[I]10\f[].
.SS Description
.PP
This template demonstrates the basic features of rapport.
We all hope you will like it!
.SS Début
.PP
Hello, world!
.PP
I have just specified a \f[I]Variable\f[] in this template named to
\f[B]leisure\f[].
The label of this variable is "Internet usage in leisure time (hours per
day)".
.PP
And wow, the mean of \f[I]leisure\f[] is \f[I]3.1994\f[]!
.PP
\f[B]For more detailed statistics, you should have set
\f[C]desc=TRUE\f[]!\f[]
.SS Description
.PP
This template demonstrates the basic features of rapport.
We all hope you will like it!
.SS Début
.PP
Hello, world!
.PP
I have just specified a \f[I]Variable\f[] in this template named to
\f[B]leisure\f[].
The label of this variable is "Internet usage in leisure time (hours per
day)".
.PP
And wow, the mean of \f[I]leisure\f[] is \f[I]3.1994\f[]!
.PP
\f[B]For more detailed statistics, you should have set
\f[C]desc=TRUE\f[]!\f[]
.SS Histogram
.PP
[IMAGE: image (9542b7929dcd934208ee4f18bde6ff31.png)]
.SS Description
.PP
This template demonstrates the basic features of rapport.
We all hope you will like it!
.SS Début
.PP
Hello, world!
.PP
I have just specified a \f[I]Variable\f[] in this template named to
\f[B]leisure\f[].
The label of this variable is "Internet usage in leisure time (hours per
day)".
.PP
And wow, the mean of \f[I]leisure\f[] is \f[I]3.1994\f[]!
.PP
\f[B]For more detailed statistics, you should have set
\f[C]desc=TRUE\f[]!\f[]
.SS Histogram
.PP
[IMAGE: image (f72d3b7413bcb88fce740c2ab229411a.png)]
.PP
   *   *   *   *   *
.PP
This report was generated with rapport (http://rapport-package.info/).
.PP
[IMAGE: image (images/rapport.png)]
.SH AUTHORS
(Username not set) (E-mail address not set).
