.\"t
.TH Example "" "2011\[en]04\[en]26 20:25 CET" "template"
.SS Description
.PP
This template demonstrates the basic features of rapport.
We all hope you will like it!
.SS Début
.PP
Hello, world!
.PP
I have just specified a \f[I]Variable\f[] in this template named to
\f[B]leisure\f[].
The label of this variable is \[lq]Internet usage in leisure time (hours
per day)\[rq].
.PP
And wow, the mean of \f[I]leisure\f[] is 3.2221!
.SS Descriptive statistics
.PP
.TS
tab(@);
l l l l l l l.
T{
T}@T{
\f[B]Min.\f[]
T}@T{
\f[B]1st Qu.\f[]
T}@T{
\f[B]Median\f[]
T}@T{
\f[B]Mean\f[]
T}@T{
\f[B]3rd Qu.\f[]
T}@T{
\f[B]Max.\f[]
T}
_
T{
1
T}@T{
0.00
T}@T{
2.00
T}@T{
3.00
T}@T{
3.22
T}@T{
4.00
T}@T{
12.00
T}
.TE
.PP
The 5 highest values are: \f[I]12\f[], \f[I]12\f[], \f[I]10\f[],
\f[I]10\f[] and \f[I]10\f[].
.SS Description
.PP
This template demonstrates the basic features of rapport.
We all hope you will like it!
.SS Début
.PP
Hello, world!
.PP
I have just specified a \f[I]Variable\f[] in this template named to
\f[B]leisure\f[].
The label of this variable is \[lq]Internet usage in leisure time (hours
per day)\[rq].
.PP
And wow, the mean of \f[I]leisure\f[] is 3.2221!
.PP
\f[B]For more detailed statistics, you should have set
\f[C]desc=TRUE\f[]!\f[]
.SS Description
.PP
This template demonstrates the basic features of rapport.
We all hope you will like it!
.SS Début
.PP
Hello, world!
.PP
I have just specified a \f[I]Variable\f[] in this template named to
\f[B]leisure\f[].
The label of this variable is \[lq]Internet usage in leisure time (hours
per day)\[rq].
.PP
And wow, the mean of \f[I]leisure\f[] is 3.2221!
.PP
\f[B]For more detailed statistics, you should have set
\f[C]desc=TRUE\f[]!\f[]
.SS Histogram
.PP
[IMAGE: image (fe9021434b8db586fac253cd0fedbfc2.png)]
.SS Description
.PP
This template demonstrates the basic features of rapport.
We all hope you will like it!
.SS Début
.PP
Hello, world!
.PP
I have just specified a \f[I]Variable\f[] in this template named to
\f[B]leisure\f[].
The label of this variable is \[lq]Internet usage in leisure time (hours
per day)\[rq].
.PP
And wow, the mean of \f[I]leisure\f[] is 3.2221!
.PP
\f[B]For more detailed statistics, you should have set
\f[C]desc=TRUE\f[]!\f[]
.SS Histogram
.PP
[IMAGE: image (3f5075e30419f077ee974a022dd89e33.png)]
.SH AUTHORS
Rapport package team \@ https://github.com/aL3xa/rapport.
