.\"t
.TH example "" "2011\[en]04\[en]26 20:25 CET" "script"
.SS Description
.PP
A simple report.
.SS Descriptive statistics
.PP
The average fuel consumption is 20.091 with SD of 6.027.
Let's add one more line to this paragraph.
And another one.
Now, you've probably heard of \f[I]pi\f[]?
Right?
Its value is 3.1416.
.SS Graphs
.PP
And some graphs:
.PP
[IMAGE: image (KKORo27NO5ORo5llNoO38oO7e2OWO2IOO757OolWmlQ87hPGOlJeOjOv5om7NP7hPGOQ5ANQOjOo8RoI5HNOholoB575oGOl8OOjOto.png)]
.PP
So far we've been dealing with data.frames and plots, now let's deal
with variables
.PP
Now we'll see if the Z var is working properly.
If I omit it, it should perserve the default value (TRUE)\&...
aaaand\&....
TRUE.
.PP
OK, so far, so good, but let's see what's going on with code chunks\&...
.PP
.TS
tab(@);
l l l l l l l l l l.
T{
0.22234
T}@T{
0.65173
T}@T{
1.39133
T}@T{
0.98333
T}@T{
\[en]0.58344
T}@T{
\[en]0.99095
T}@T{
\[en]0.45373
T}@T{
\[en]0.65796
T}@T{
2.37939
T}@T{
2.06748
T}
T{
\[en]0.31492
T}@T{
\[en]0.84771
T}@T{
\[en]0.55026
T}@T{
0.91617
T}@T{
\[en]0.16968
T}@T{
1.27141
T}@T{
0.46340
T}@T{
\[en]0.10636
T}@T{
\[en]0.18371
T}@T{
\[en]0.24102
T}
T{
0.07103
T}@T{
0.00653
T}@T{
\[en]0.35326
T}@T{
0.81124
T}@T{
0.17430
T}@T{
\[en]0.15579
T}@T{
\[en]0.14371
T}@T{
1.03454
T}@T{
\[en]0.11201
T}@T{
0.77493
T}
T{
0.85391
T}@T{
\[en]1.71403
T}@T{
0.53827
T}@T{
0.22948
T}@T{
0.32925
T}@T{
\[en]0.39897
T}@T{
1.07016
T}@T{
\[en]1.15996
T}@T{
\[en]0.04254
T}@T{
0.99816
T}
T{
1.84811
T}@T{
\[en]1.97597
T}@T{
1.90410
T}@T{
0.29464
T}@T{
\[en]0.26010
T}@T{
0.05813
T}@T{
\[en]1.38199
T}@T{
0.54703
T}@T{
\[en]0.05245
T}@T{
0.24624
T}
T{
\[en]0.74688
T}@T{
1.50558
T}@T{
\[en]0.13179
T}@T{
1.68098
T}@T{
1.29912
T}@T{
0.21735
T}@T{
0.89660
T}@T{
0.09138
T}@T{
\[en]0.31560
T}@T{
0.93897
T}
T{
\[en]1.55898
T}@T{
3.47041
T}@T{
1.33684
T}@T{
0.26634
T}@T{
\[en]0.14000
T}@T{
0.42141
T}@T{
\[en]0.14711
T}@T{
\[en]0.91866
T}@T{
\[en]1.73281
T}@T{
0.48034
T}
T{
\[en]1.08743
T}@T{
\[en]0.62727
T}@T{
0.58817
T}@T{
\[en]1.52503
T}@T{
\[en]0.61666
T}@T{
0.03544
T}@T{
\[en]0.87532
T}@T{
0.41800
T}@T{
\[en]0.49410
T}@T{
\[en]0.47320
T}
T{
\[en]0.14827
T}@T{
\[en]0.08834
T}@T{
\[en]1.65963
T}@T{
0.34622
T}@T{
0.59807
T}@T{
0.13834
T}@T{
0.62300
T}@T{
0.74279
T}@T{
0.71904
T}@T{
1.04388
T}
T{
\[en]0.65230
T}@T{
\[en]0.71892
T}@T{
\[en]2.85295
T}@T{
0.08785
T}@T{
\[en]0.30507
T}@T{
\[en]1.72776
T}@T{
0.76428
T}@T{
1.77922
T}@T{
1.05258
T}@T{
1.01411
T}
.TE
.PP
When it comes to CSV values, let us see how do they work.
You have chosen the \[lq]foo\[rq].
.SH AUTHORS
Rapport package team \@ https://github.com/aL3xa/rapport.
