.\"t
.TH Descriptives "" "2011\[en]04\[en]26 20:25 CET" 
.SS Description
.PP
This template will return descriptive statistics of numerical, or
frequency tables of categorical variables.
.SS \f[I]gender\f[] (\[lq]Gender\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]gender\f[] (\[lq]Gender\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]gender\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cum.n\f[]
T}@T{
\f[B]cum.pct\f[]
T}
_
T{
male
T}@T{
7344.00
T}@T{
60.93
T}@T{
7344.00
T}@T{
60.93
T}
T{
female
T}@T{
4709.00
T}@T{
39.07
T}@T{
12053.00
T}@T{
100.00
T}
.TE
.SS Barplot
.PP
[IMAGE: image (/tmp/RtmpMBlCON/file3b743a1a.png)]
.PP
It seems that the highest value is 2 which is exactly 2 times higher
than the smallest value (1).
.SS \f[I]age\f[]
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]age\f[].
This variable seems to be numeric.
.SS Base statistics
.PP
.TS
tab(@);
l l l l.
T{
\f[B]value\f[]
T}@T{
\f[B]mean\f[]
T}@T{
\f[B]sd\f[]
T}@T{
\f[B]var\f[]
T}
_
T{
(all)
T}@T{
24.56
T}@T{
6.84
T}@T{
46.78
T}
.TE
.SS Histogram
.PP
[IMAGE: image (/tmp/RtmpMBlCON/file98a4723.png)]
.PP
It seems that the highest value is 58 which is exactly 3.625 times
higher than the smallest value (16).
.SS Description
.PP
This template will return descriptive statistics of numerical, or
frequency tables of categorical variables.
.SS \f[I]chatim\f[] (\[lq]Chat & IM usage\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]chatim\f[] (\[lq]Chat & IM usage\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]chatim\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cum.n\f[]
T}@T{
\f[B]cum.pct\f[]
T}
_
T{
never
T}@T{
896.00
T}@T{
9.03
T}@T{
896.00
T}@T{
9.03
T}
T{
very rarely
T}@T{
1092.00
T}@T{
11.00
T}@T{
1988.00
T}@T{
20.03
T}
T{
rarely
T}@T{
910.00
T}@T{
9.17
T}@T{
2898.00
T}@T{
29.20
T}
T{
sometimes
T}@T{
1736.00
T}@T{
17.49
T}@T{
4634.00
T}@T{
46.69
T}
T{
often
T}@T{
1988.00
T}@T{
20.03
T}@T{
6622.00
T}@T{
66.71
T}
T{
very often
T}@T{
1316.00
T}@T{
13.26
T}@T{
7938.00
T}@T{
79.97
T}
T{
always
T}@T{
1988.00
T}@T{
20.03
T}@T{
9926.00
T}@T{
100.00
T}
.TE
.PP
\f[B]Warning\f[] in \[lq]if (is.numeric(var)) { ; rp.desc(NULL,
rp.name(var), c(`mean', `sd', `var'), rp.data) ; } else { ;
rp.freq(rp.name(var), rp.data) ; }\[rq]: \[lq]invalid factor level, NAs
generated + invalid factor level, NAs generated + invalid factor level,
NAs generated\[rq]
.SS Barplot
.PP
[IMAGE: image (/tmp/RtmpMBlCON/file7eb47e7a.png)]
.PP
It seems that the highest value is 7 which is exactly 7 times higher
than the smallest value (1).
.SS \f[I]game\f[] (\[lq]On-line games usage\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]game\f[] (\[lq]On-line games usage\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]game\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cum.n\f[]
T}@T{
\f[B]cum.pct\f[]
T}
_
T{
never
T}@T{
5152.00
T}@T{
51.90
T}@T{
5152.00
T}@T{
51.90
T}
T{
very rarely
T}@T{
1848.00
T}@T{
18.62
T}@T{
7000.00
T}@T{
70.52
T}
T{
rarely
T}@T{
490.00
T}@T{
4.94
T}@T{
7490.00
T}@T{
75.46
T}
T{
sometimes
T}@T{
910.00
T}@T{
9.17
T}@T{
8400.00
T}@T{
84.63
T}
T{
often
T}@T{
532.00
T}@T{
5.36
T}@T{
8932.00
T}@T{
89.99
T}
T{
very often
T}@T{
518.00
T}@T{
5.22
T}@T{
9450.00
T}@T{
95.20
T}
T{
always
T}@T{
476.00
T}@T{
4.80
T}@T{
9926.00
T}@T{
100.00
T}
.TE
.PP
\f[B]Warning\f[] in \[lq]if (is.numeric(var)) { ; rp.desc(NULL,
rp.name(var), c(`mean', `sd', `var'), rp.data) ; } else { ;
rp.freq(rp.name(var), rp.data) ; }\[rq]: \[lq]invalid factor level, NAs
generated + invalid factor level, NAs generated + invalid factor level,
NAs generated\[rq]
.SS Barplot
.PP
[IMAGE: image (/tmp/RtmpMBlCON/file5546bd02.png)]
.PP
It seems that the highest value is 7 which is exactly 7 times higher
than the smallest value (1).
.SS \f[I]surf\f[] (\[lq]Web surfing usage\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]surf\f[] (\[lq]Web surfing usage\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]surf\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cum.n\f[]
T}@T{
\f[B]cum.pct\f[]
T}
_
T{
never
T}@T{
238.00
T}@T{
2.40
T}@T{
238.00
T}@T{
2.40
T}
T{
very rarely
T}@T{
364.00
T}@T{
3.67
T}@T{
602.00
T}@T{
6.06
T}
T{
rarely
T}@T{
476.00
T}@T{
4.80
T}@T{
1078.00
T}@T{
10.86
T}
T{
sometimes
T}@T{
1624.00
T}@T{
16.36
T}@T{
2702.00
T}@T{
27.22
T}
T{
often
T}@T{
2296.00
T}@T{
23.13
T}@T{
4998.00
T}@T{
50.35
T}
T{
very often
T}@T{
2114.00
T}@T{
21.30
T}@T{
7112.00
T}@T{
71.65
T}
T{
always
T}@T{
2814.00
T}@T{
28.35
T}@T{
9926.00
T}@T{
100.00
T}
.TE
.PP
\f[B]Warning\f[] in \[lq]if (is.numeric(var)) { ; rp.desc(NULL,
rp.name(var), c(`mean', `sd', `var'), rp.data) ; } else { ;
rp.freq(rp.name(var), rp.data) ; }\[rq]: \[lq]invalid factor level, NAs
generated + invalid factor level, NAs generated + invalid factor level,
NAs generated\[rq]
.SS Barplot
.PP
[IMAGE: image (/tmp/RtmpMBlCON/file6b2b43aa.png)]
.PP
It seems that the highest value is 7 which is exactly 7 times higher
than the smallest value (1).
.SS \f[I]email\f[] (\[lq]Email usage\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]email\f[] (\[lq]Email usage\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]email\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cum.n\f[]
T}@T{
\f[B]cum.pct\f[]
T}
_
T{
never
T}@T{
182.00
T}@T{
1.83
T}@T{
182.00
T}@T{
1.83
T}
T{
very rarely
T}@T{
532.00
T}@T{
5.36
T}@T{
714.00
T}@T{
7.19
T}
T{
rarely
T}@T{
714.00
T}@T{
7.19
T}@T{
1428.00
T}@T{
14.39
T}
T{
sometimes
T}@T{
1260.00
T}@T{
12.69
T}@T{
2688.00
T}@T{
27.08
T}
T{
often
T}@T{
1806.00
T}@T{
18.19
T}@T{
4494.00
T}@T{
45.28
T}
T{
very often
T}@T{
1624.00
T}@T{
16.36
T}@T{
6118.00
T}@T{
61.64
T}
T{
always
T}@T{
3808.00
T}@T{
38.36
T}@T{
9926.00
T}@T{
100.00
T}
.TE
.PP
\f[B]Warning\f[] in \[lq]if (is.numeric(var)) { ; rp.desc(NULL,
rp.name(var), c(`mean', `sd', `var'), rp.data) ; } else { ;
rp.freq(rp.name(var), rp.data) ; }\[rq]: \[lq]invalid factor level, NAs
generated + invalid factor level, NAs generated + invalid factor level,
NAs generated\[rq]
.SS Barplot
.PP
[IMAGE: image (/tmp/RtmpMBlCON/file10be4543.png)]
.PP
It seems that the highest value is 7 which is exactly 7 times higher
than the smallest value (1).
.SS \f[I]download\f[] (\[lq]Download usage\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]download\f[] (\[lq]Download usage\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]download\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cum.n\f[]
T}@T{
\f[B]cum.pct\f[]
T}
_
T{
never
T}@T{
154.00
T}@T{
1.55
T}@T{
154.00
T}@T{
1.55
T}
T{
very rarely
T}@T{
406.00
T}@T{
4.09
T}@T{
560.00
T}@T{
5.64
T}
T{
rarely
T}@T{
420.00
T}@T{
4.23
T}@T{
980.00
T}@T{
9.87
T}
T{
sometimes
T}@T{
1190.00
T}@T{
11.99
T}@T{
2170.00
T}@T{
21.86
T}
T{
often
T}@T{
1820.00
T}@T{
18.34
T}@T{
3990.00
T}@T{
40.20
T}
T{
very often
T}@T{
2394.00
T}@T{
24.12
T}@T{
6384.00
T}@T{
64.32
T}
T{
always
T}@T{
3542.00
T}@T{
35.68
T}@T{
9926.00
T}@T{
100.00
T}
.TE
.PP
\f[B]Warning\f[] in \[lq]if (is.numeric(var)) { ; rp.desc(NULL,
rp.name(var), c(`mean', `sd', `var'), rp.data) ; } else { ;
rp.freq(rp.name(var), rp.data) ; }\[rq]: \[lq]invalid factor level, NAs
generated + invalid factor level, NAs generated + invalid factor level,
NAs generated\[rq]
.SS Barplot
.PP
[IMAGE: image (/tmp/RtmpMBlCON/file46b8f0e.png)]
.PP
It seems that the highest value is 7 which is exactly 7 times higher
than the smallest value (1).
.SS \f[I]forum\f[] (\[lq]Web forums usage\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]forum\f[] (\[lq]Web forums usage\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]forum\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cum.n\f[]
T}@T{
\f[B]cum.pct\f[]
T}
_
T{
never
T}@T{
1120.00
T}@T{
11.28
T}@T{
1120.00
T}@T{
11.28
T}
T{
very rarely
T}@T{
1176.00
T}@T{
11.85
T}@T{
2296.00
T}@T{
23.13
T}
T{
rarely
T}@T{
1036.00
T}@T{
10.44
T}@T{
3332.00
T}@T{
33.57
T}
T{
sometimes
T}@T{
1736.00
T}@T{
17.49
T}@T{
5068.00
T}@T{
51.06
T}
T{
often
T}@T{
1568.00
T}@T{
15.80
T}@T{
6636.00
T}@T{
66.85
T}
T{
very often
T}@T{
1750.00
T}@T{
17.63
T}@T{
8386.00
T}@T{
84.49
T}
T{
always
T}@T{
1540.00
T}@T{
15.51
T}@T{
9926.00
T}@T{
100.00
T}
.TE
.PP
\f[B]Warning\f[] in \[lq]if (is.numeric(var)) { ; rp.desc(NULL,
rp.name(var), c(`mean', `sd', `var'), rp.data) ; } else { ;
rp.freq(rp.name(var), rp.data) ; }\[rq]: \[lq]invalid factor level, NAs
generated + invalid factor level, NAs generated + invalid factor level,
NAs generated\[rq]
.SS Barplot
.PP
[IMAGE: image (/tmp/RtmpMBlCON/file7a7e9726.png)]
.PP
It seems that the highest value is 7 which is exactly 7 times higher
than the smallest value (1).
.SS \f[I]socnet\f[] (\[lq]Social networks usage\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]socnet\f[] (\[lq]Social networks usage\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]socnet\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cum.n\f[]
T}@T{
\f[B]cum.pct\f[]
T}
_
T{
never
T}@T{
2940.00
T}@T{
29.62
T}@T{
2940.00
T}@T{
29.62
T}
T{
very rarely
T}@T{
1554.00
T}@T{
15.66
T}@T{
4494.00
T}@T{
45.28
T}
T{
rarely
T}@T{
826.00
T}@T{
8.32
T}@T{
5320.00
T}@T{
53.60
T}
T{
sometimes
T}@T{
1316.00
T}@T{
13.26
T}@T{
6636.00
T}@T{
66.85
T}
T{
often
T}@T{
1148.00
T}@T{
11.57
T}@T{
7784.00
T}@T{
78.42
T}
T{
very often
T}@T{
1190.00
T}@T{
11.99
T}@T{
8974.00
T}@T{
90.41
T}
T{
always
T}@T{
952.00
T}@T{
9.59
T}@T{
9926.00
T}@T{
100.00
T}
.TE
.PP
\f[B]Warning\f[] in \[lq]if (is.numeric(var)) { ; rp.desc(NULL,
rp.name(var), c(`mean', `sd', `var'), rp.data) ; } else { ;
rp.freq(rp.name(var), rp.data) ; }\[rq]: \[lq]invalid factor level, NAs
generated + invalid factor level, NAs generated + invalid factor level,
NAs generated\[rq]
.SS Barplot
.PP
[IMAGE: image (/tmp/RtmpMBlCON/file7a050d7b.png)]
.PP
It seems that the highest value is 7 which is exactly 7 times higher
than the smallest value (1).
.SS \f[I]xxx\f[] (\[lq]Adult sites usage\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]xxx\f[] (\[lq]Adult sites usage\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]xxx\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cum.n\f[]
T}@T{
\f[B]cum.pct\f[]
T}
_
T{
never
T}@T{
4102.00
T}@T{
41.33
T}@T{
4102.00
T}@T{
41.33
T}
T{
very rarely
T}@T{
1792.00
T}@T{
18.05
T}@T{
5894.00
T}@T{
59.38
T}
T{
rarely
T}@T{
770.00
T}@T{
7.76
T}@T{
6664.00
T}@T{
67.14
T}
T{
sometimes
T}@T{
1918.00
T}@T{
19.32
T}@T{
8582.00
T}@T{
86.46
T}
T{
often
T}@T{
672.00
T}@T{
6.77
T}@T{
9254.00
T}@T{
93.23
T}
T{
very often
T}@T{
406.00
T}@T{
4.09
T}@T{
9660.00
T}@T{
97.32
T}
T{
always
T}@T{
266.00
T}@T{
2.68
T}@T{
9926.00
T}@T{
100.00
T}
.TE
.PP
\f[B]Warning\f[] in \[lq]if (is.numeric(var)) { ; rp.desc(NULL,
rp.name(var), c(`mean', `sd', `var'), rp.data) ; } else { ;
rp.freq(rp.name(var), rp.data) ; }\[rq]: \[lq]invalid factor level, NAs
generated + invalid factor level, NAs generated + invalid factor level,
NAs generated\[rq]
.SS Barplot
.PP
[IMAGE: image (/tmp/RtmpMBlCON/file21419ce0.png)]
.PP
It seems that the highest value is 7 which is exactly 7 times higher
than the smallest value (1).
.SS \f[I]long.use\f[] (\[lq]How long you've been on the Internet?\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]long.use\f[] (\[lq]How long you've been on the Internet?\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]long.use\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cum.n\f[]
T}@T{
\f[B]cum.pct\f[]
T}
_
T{
less than 6 months
T}@T{
294.00
T}@T{
2.96
T}@T{
294.00
T}@T{
2.96
T}
T{
1 years
T}@T{
728.00
T}@T{
7.33
T}@T{
1022.00
T}@T{
10.30
T}
T{
2 years
T}@T{
966.00
T}@T{
9.73
T}@T{
1988.00
T}@T{
20.03
T}
T{
3 years
T}@T{
1092.00
T}@T{
11.00
T}@T{
3080.00
T}@T{
31.03
T}
T{
4 years
T}@T{
1064.00
T}@T{
10.72
T}@T{
4144.00
T}@T{
41.75
T}
T{
5 years
T}@T{
1036.00
T}@T{
10.44
T}@T{
5180.00
T}@T{
52.19
T}
T{
5 years and more
T}@T{
4746.00
T}@T{
47.81
T}@T{
9926.00
T}@T{
100.00
T}
.TE
.PP
\f[B]Warning\f[] in \[lq]if (is.numeric(var)) { ; rp.desc(NULL,
rp.name(var), c(`mean', `sd', `var'), rp.data) ; } else { ;
rp.freq(rp.name(var), rp.data) ; }\[rq]: \[lq]invalid factor level, NAs
generated + invalid factor level, NAs generated + invalid factor level,
NAs generated\[rq]
.SS Barplot
.PP
[IMAGE: image (/tmp/RtmpMBlCON/file6acfe10f.png)]
.PP
It seems that the highest value is 7 which is exactly 7 times higher
than the smallest value (1).
.SH AUTHORS
Rapport package team \@ https://github.com/aL3xa/rapport.
