.\"t
.TH Outlier "" "2011\[en]04\[en]26 20:25 CET" "test"
.SS Description
.PP
This template will check if provided variable has any outliers.
.SS Boxplot
.PP
[IMAGE: image (d24b3eb41da4d1de21d4bce0e30d2e1b.png)]
.SS Lund test
.PP
It seems that 4 extreme values can be found in \[lq]Internet usage for
educational purposes (hours per day)\[rq].
These are: 10, 0.5, 1.5, 0.5.
.SS Explanation
.PP
The above test for outliers was based on \f[I]lm(1 ~ edu)\f[]:
.PP
.TS
tab(@);
l l l l l.
T{
T}@T{
\f[B]Estimate\f[]
T}@T{
\f[B]Std. Error\f[]
T}@T{
\f[B]t value\f[]
T}@T{
\f[B]Pr(>|t|)\f[]
T}
_
T{
(Intercept)
T}@T{
2.05
T}@T{
0.08
T}@T{
26.27
T}@T{
0.00
T}
.TE
.SS References
.IP \[bu] 2
Lund, R.
E.
1975, \[lq]Tables for An Approximate Test for Outliers in Linear
Models\[rq], Technometrics, vol.\ 17, no.
4, pp.\ 473\[en]476.
.IP \[bu] 2
Prescott, P.
1975, \[lq]An Approximate Test for Outliers in Linear Models\[rq],
Technometrics, vol.\ 17, no.
1, pp.\ 129\[en]132.
.SS Grubb's test
.PP
Grubbs test for one outlier shows that highest value 12 is an outlier
(p=0.0002).
.SS References
.IP \[bu] 2
Grubbs, F.E.
(1950).
Sample Criteria for testing outlying observations.
Ann.
Math.
Stat.
21, 1, 27\[en]58.
.SS Dixon's test
.PP
chi-squared test for outlier shows that highest value 12 is an outlier
(p=0).
.SS References
.IP \[bu] 2
Dixon, W.J.
(1950).
Analysis of extreme values.
Ann.
Math.
Stat.
21, 4, 488\[en]506.
.SS Description
.PP
This template will check if provided variable has any outliers.
.SS Boxplot
.PP
[IMAGE: image (d24b3eb41da4d1de21d4bce0e30d2e1b.png)]
.SS Lund test
.PP
It seems that 4 extreme values can be found in \[lq]Internet usage for
educational purposes (hours per day)\[rq].
These are: 10, 0.5, 1.5, 0.5.
.SS Explanation
.PP
The above test for outliers was based on \f[I]lm(1 ~ edu)\f[]:
.PP
.TS
tab(@);
l l l l l.
T{
T}@T{
\f[B]Estimate\f[]
T}@T{
\f[B]Std. Error\f[]
T}@T{
\f[B]t value\f[]
T}@T{
\f[B]Pr(>|t|)\f[]
T}
_
T{
(Intercept)
T}@T{
2.05
T}@T{
0.08
T}@T{
26.27
T}@T{
0.00
T}
.TE
.SS References
.IP \[bu] 2
Lund, R.
E.
1975, \[lq]Tables for An Approximate Test for Outliers in Linear
Models\[rq], Technometrics, vol.\ 17, no.
4, pp.\ 473\[en]476.
.IP \[bu] 2
Prescott, P.
1975, \[lq]An Approximate Test for Outliers in Linear Models\[rq],
Technometrics, vol.\ 17, no.
1, pp.\ 129\[en]132.
.SS Grubb's test
.PP
Grubbs test for one outlier shows that highest value 12 is an outlier
(p=0.0002).
.SS References
.IP \[bu] 2
Grubbs, F.E.
(1950).
Sample Criteria for testing outlying observations.
Ann.
Math.
Stat.
21, 1, 27\[en]58.
.SS Dixon's test
.PP
chi-squared test for outlier shows that highest value 12 is an outlier
(p=0).
.SS References
.IP \[bu] 2
Dixon, W.J.
(1950).
Analysis of extreme values.
Ann.
Math.
Stat.
21, 4, 488\[en]506.
.SS Description
.PP
This template will check if provided variable has any outliers.
.SS Boxplot
.PP
[IMAGE: image (d24b3eb41da4d1de21d4bce0e30d2e1b.png)]
.SS Lund test
.PP
It seems that 4 extreme values can be found in \[lq]Internet usage for
educational purposes (hours per day)\[rq].
These are: 10, 0.5, 1.5, 0.5.
.SS Explanation
.PP
The above test for outliers was based on \f[I]lm(1 ~ edu)\f[]:
.PP
.TS
tab(@);
l l l l l.
T{
T}@T{
\f[B]Estimate\f[]
T}@T{
\f[B]Std. Error\f[]
T}@T{
\f[B]t value\f[]
T}@T{
\f[B]Pr(>|t|)\f[]
T}
_
T{
(Intercept)
T}@T{
2.05
T}@T{
0.08
T}@T{
26.27
T}@T{
0.00
T}
.TE
.SH AUTHORS
Rapport package team \@ https://github.com/aL3xa/rapport.
