.\"t
.TH Descriptives "" "2011\[en]04\[en]26 20:25 CET" 
.SS Description
.PP
This template will return descriptive statistics of a numerical, or a
frequency table of a categorical variable.
.SS \f[I]gender\f[] (\[lq]Gender\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]gender\f[] (\[lq]Gender\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l.
T{
\f[B]gender\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cum.n\f[]
T}@T{
\f[B]cum.pct\f[]
T}
_
T{
male
T}@T{
7344.00
T}@T{
60.93
T}@T{
7344.00
T}@T{
60.93
T}
T{
female
T}@T{
4709.00
T}@T{
39.07
T}@T{
12053.00
T}@T{
100.00
T}
.TE
.SS Barplot
.PP
[IMAGE: image (2a42fb1eb44bf1361b44216c6b0c16ee.png)]
.PP
It seems that the highest value is 2 which is exactly 2 times higher
than the smallest value (1).
.SS Description
.PP
This template will return descriptive statistics of a numerical, or a
frequency table of a categorical variable.
.SS \f[I]age\f[] (\[lq]Age\[rq])
.PP
The dataset has 709 observations with 709 valid values (missing: 0) in
\f[I]age\f[] (\[lq]Age\[rq]).
This variable seems to be numeric.
.SS Base statistics
.PP
.TS
tab(@);
l l l l.
T{
\f[B]value\f[]
T}@T{
\f[B]mean\f[]
T}@T{
\f[B]sd\f[]
T}@T{
\f[B]var\f[]
T}
_
T{
(all)
T}@T{
24.56
T}@T{
6.84
T}@T{
46.78
T}
.TE
.SS Histogram
.PP
[IMAGE: image (76fc57f9d2387aff730be60323f25624.png)]
.PP
It seems that the highest value is 58 which is exactly 3.625 times
higher than the smallest value (16).
.PP
The standard deviation is 6.8399 (variance: 46.784).
The expected value is around 24.557, somewhere between 24.054 and 25.061
(SE: 0.2569).
.PP
If we suppose that \f[I]Age\f[] is not near to a normal distribution
(test: , skewness: 1.9568, kurtosis: 7.6428), checking the median (23)
might be a better option instead of the mean.
The interquartile range (6) measures the statistics dispersion of the
variable (similar to standard deviation) based on median.
.SH AUTHORS
(Username not set) (E-mail address not set).
