.\"t
.TH Descriptives "" "2011\[en]04\[en]26 20:25 CET" 
.SS Description
.PP
This template will return descriptive statistics of a numerical, or a
frequency table of a categorical variable.
.SS \f[I]gender\f[] (\[lq]Gender\[rq])
.PP
The dataset has 709 observations with 673 valid values (missing: 36) in
\f[I]gender\f[] (\[lq]Gender\[rq]).
This variable seems to be a factor.
.SS Base statistics
.PP
.TS
tab(@);
l l l l l l.
T{
T}@T{
\f[B]gender\f[]
T}@T{
\f[B]N\f[]
T}@T{
\f[B]pct\f[]
T}@T{
\f[B]cumul.count\f[]
T}@T{
\f[B]cumul.pct\f[]
T}
_
T{
1
T}@T{
male
T}@T{
410.00
T}@T{
60.92
T}@T{
410.00
T}@T{
60.92
T}
T{
2
T}@T{
female
T}@T{
263.00
T}@T{
39.08
T}@T{
673.00
T}@T{
100.00
T}
T{
Total
T}@T{
T}@T{
673.00
T}@T{
100.00
T}@T{
673.00
T}@T{
100.00
T}
.TE
.SS Barplot
.PP
[IMAGE: image (3ed92ab3ffc6e875335e7e8c774c35a8.png)]
.PP
It seems that the highest value is 2 which is exactly 2 times higher
than the smallest value (1).
.SS Description
.PP
This template will return descriptive statistics of a numerical, or a
frequency table of a categorical variable.
.SS \f[I]age\f[] (\[lq]Age\[rq])
.PP
The dataset has 709 observations with 677 valid values (missing: 32) in
\f[I]age\f[] (\[lq]Age\[rq]).
This variable seems to be numeric.
.SS Base statistics
.PP
.TS
tab(@);
l l l l.
T{
\f[B]value\f[]
T}@T{
\f[B]mean(age)\f[]
T}@T{
\f[B]sd(age)\f[]
T}@T{
\f[B]var(age)\f[]
T}
_
T{
(all)
T}@T{
24.57
T}@T{
6.85
T}@T{
46.91
T}
.TE
.SS Histogram
.PP
[IMAGE: image (ac5d789145bdef09b10219ef16429f53.png)]
.PP
It seems that the highest value is 58 which is exactly 3.625 times
higher than the smallest value (16).
.PP
The standard deviation is 6.8491 (variance: 46.911).
The expected value is around 24.573, somewhere between 24.057 and 25.089
(SE: 0.2632).
.PP
If we suppose that \f[I]Age\f[] is not near to a normal distribution
(test: , skewness: 1.9296, kurtosis: 7.4851), checking the median (23)
might be a better option instead of the mean.
The interquartile range (6) measures the statistics dispersion of the
variable (similar to standard deviation) based on median.
.SH AUTHORS
Rapport package team \@ https://github.com/aL3xa/rapport.
